/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package training_project;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static training_project.Training_project.connect_me;

/**
 *
 * @author AMN
 */
public class month_frame extends javax.swing.JFrame {

    /**
     * Creates new form month_frame
     */
    public month_frame() {
        
        this.setResizable(false);
        this.setVisible(true);
        initComponents();
         this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        newlesson = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        price = new javax.swing.JTextField();
        telephone = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        name = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        newlesson.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        newlesson.setText("new lesson");
        newlesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newlessonActionPerformed(evt);
            }
        });
        jPanel1.add(newlesson);
        newlesson.setBounds(400, 310, 140, 30);

        jLabel4.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 5, 255));
        jLabel4.setText("number of lesson");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 310, 190, 30);

        jLabel3.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("0");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(240, 310, 130, 30);

        jButton2.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jButton2.setText("cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(570, 310, 200, 30);

        jButton1.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jButton1.setText("insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(520, 210, 240, 40);
        jPanel1.add(price);
        price.setBounds(230, 270, 240, 30);
        jPanel1.add(telephone);
        telephone.setBounds(230, 220, 240, 30);
        jPanel1.add(city);
        city.setBounds(230, 170, 240, 30);
        jPanel1.add(age);
        age.setBounds(230, 120, 240, 30);

        jComboBox1.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 5, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "sowina", "fitness", "bodyBuilding" }));
        jComboBox1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(230, 20, 240, 30);
        jPanel1.add(name);
        name.setBounds(230, 70, 240, 30);

        jLabel12.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 5, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("price");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(50, 270, 170, 20);

        jLabel11.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 5, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("telephone");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(40, 220, 170, 20);

        jLabel10.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 5, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("city");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 180, 170, 20);

        jLabel9.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 5, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("age");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 130, 170, 20);

        jLabel8.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 5, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("name");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 80, 170, 20);

        jLabel2.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 5, 255));
        jLabel2.setText("kind of training");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 20, 170, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/training_project/asdddd.jpeg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 780, 350);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        menu_frame om = new menu_frame();
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String jname = this.name.getText();
        //System.out.println("**"+jname+"**");
        String jage = this.age.getText();
        String jprice = this.price.getText();
        String jphone  = this.telephone.getText();
         String jtraining = (String )this.jComboBox1.getSelectedItem();
         
       
        String jcity = this.city.getText();
        String jhasah=this.jLabel3.getText();
        
        if( this.price.getText().isEmpty() && this.name.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "complete the data ");
            
        } 
       else
        {
          String SQL  = "INSERT INTO gym.monthly_training "
                      + "( name , phone , price , king_of_training , city ,age, hasa_number  ) "
                      + "VALUES ( \" "
                      + jname  +"\""
                      +"," +"\""
                      + jphone +"\""
                      +","
                      +jprice
                      +","+"\""
                      +jtraining+"\""
                      +","+"\""
                      +jcity+"\""
                      + ","
                      + jage+","
                      +jhasah
                      + " )";
            
            
          //  System.out.println(SQL);
            try {
                connect_me.insert_function(SQL);
            } catch (SQLException ex) {
                Logger.getLogger(second.class.getName()).log(Level.SEVERE, null, ex);
            }
                    
            
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void newlessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newlessonActionPerformed
       int num=Integer.parseInt(jLabel3.getText())+1;
        System.out.println(num);
       jLabel3.setText(String.valueOf(num));
       
        
    }//GEN-LAST:event_newlessonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(month_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(month_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(month_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(month_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new month_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JTextField city;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JButton newlesson;
    private javax.swing.JTextField price;
    private javax.swing.JTextField telephone;
    // End of variables declaration//GEN-END:variables
}
