/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package training_project;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author AMN
 */
public class search_frame2 extends javax.swing.JFrame {

    private DefaultListModel model;
    private ArrayList<Integer> ides = new ArrayList<>();

    ;

    /**
     * Creates new form search_frame2
     */
    public search_frame2() {
        
        this.setResizable(false);
        this.setVisible(true);
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        open_item = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        search = new javax.swing.JButton();
        query = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        open_item.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        open_item.setText("open selected item");
        open_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_itemActionPerformed(evt);
            }
        });
        jPanel1.add(open_item);
        open_item.setBounds(5, 290, 260, 40);

        close.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        close.setText("close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel1.add(close);
        close.setBounds(530, 300, 200, 40);

        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 80, 380, 200);

        search.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        search.setText("search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search);
        search.setBounds(400, 180, 330, 30);
        jPanel1.add(query);
        query.setBounds(530, 80, 200, 30);

        jLabel2.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("name");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(400, 80, 110, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "hasa", "monthly_training" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(500, 20, 230, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/training_project/asdddd.jpeg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 740, 350);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here: 
        menu_frame on = new menu_frame();
        this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed

        // TODO add your handling code here:
        String SQL;
        String namme = this.query.getText();
        if (this.jComboBox1.getSelectedItem() == "hasa") {
            try {
                SQL = "Select * from gym.hasa  where name Like \"%" + namme + "%\";";
                String name;
                int age;
                Search_result = Training_project.connect_me.Select(SQL);
                Search_result.first();
                model = new DefaultListModel();
                if (Search_result.next()) {
                    Search_result.first();
                    do {
                        name = Search_result.getString("name");
                        age = Search_result.getInt("age");

                        ides.add(Search_result.getInt("idhasa"));
                        name = name + "                " + String.valueOf(age);
                        model.addElement(name);
                        //System.out.println(name);

                    } while (Search_result.next());
                }
                Search_result.first();
                this.jList1.setModel(model);
            } catch (SQLException ex) {
                Logger.getLogger(search_frame2.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            try {
                SQL = "Select * from gym.monthly_training where name Like \"%" + namme + "%\";";
                String name;
                int age;
                Search_result = Training_project.connect_me.Select(SQL);
                Search_result.first();
                model = new DefaultListModel();
                if (Search_result.next()) {
                    try {
                        Search_result.first();
                        do {
                            name = Search_result.getString("name");
                            age = Search_result.getInt("age");

                            ides.add(Search_result.getInt("ida4trak"));
                            name = name + "    " + String.valueOf(age);
                            model.addElement(name);
                            //System.out.println(name);

                        } while (Search_result.next());
                        Search_result.first();
                    } catch (SQLException ex) {
                        Logger.getLogger(search_frame2.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                this.jList1.setModel(model);
            } catch (SQLException ex) {
                Logger.getLogger(search_frame2.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
            // System.out.println(SQL);


    }//GEN-LAST:event_searchActionPerformed

    private void open_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_itemActionPerformed

        String SQL;
        try {
            // TODO add your handling code here:..

            int index = this.jList1.getSelectedIndex();
           // System.out.println(index);
            int id = ides.get(index);
            //System.out.println("*******************" + id);
            // System.out.println(id);
            if (this.jComboBox1.getSelectedItem() == "hasa") {
                SQL = "select * from  gym.hasa where idhasa = " + id;
                System.out.println(SQL);
                Search_result2 = Training_project.connect_me.Select(SQL);
                Search_result2.first();
                String jname = this.Search_result2.getString("name");
                String jage = String.valueOf(this.Search_result2.getInt("age"));
                String jprice = this.Search_result2.getString("price");
                String jphone = this.Search_result2.getString("phone");
                String jtraining = this.Search_result2.getString("training_kind");
                String jcity = this.Search_result2.getString("city");
                int idhasa = this.Search_result2.getInt("idhasa");
                secondUpdate mon = new secondUpdate();
                mon.setData(jname,jage,jprice,jphone,jtraining ,jcity , idhasa );

            } else {
                SQL = "select * from  gym.monthly_training where ida4trak = " + id;
                Search_result2 = Training_project.connect_me.Select(SQL);
                Search_result2.first();
                String jname = this.Search_result2.getString("name");
                String jage = String.valueOf(this.Search_result2.getInt("age"));
                String jprice = this.Search_result2.getString("price");
                String jphone = this.Search_result2.getString("phone");
                String jtraining = this.Search_result2.getString("king_of_training");
                String jcity = this.Search_result2.getString("city");
                int hasa_number = this.Search_result2.getInt("hasa_number");
                int idhasa = this.Search_result2.getInt("ida4trak");
                month_frame_Update mon = new  month_frame_Update();
                mon.setData(jname,jage,jprice,jphone,jtraining ,jcity , idhasa ,hasa_number);
            }
             this.dispose();
            //System.out.println(SQL);
        } catch (SQLException ex) {
            Logger.getLogger(search_frame2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_open_itemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search_frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search_frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search_frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search_frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search_frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton open_item;
    private javax.swing.JTextField query;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables

    private ResultSet Search_result;
    private ResultSet Search_result2;
}
