/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package training_project;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static training_project.Training_project.connect_me;

/**
 *
 * @author AMN
 */
public class second extends javax.swing.JFrame {

    /**
     * Creates new form second
     */
    public second() {
        this.setVisible(true);
        
        this.setResizable(false);
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        price = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        compo_training = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jButton2.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        jButton2.setText("cancel");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(670, 290, 160, 30);

        jButton1.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        jButton1.setText("Insert");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(330, 290, 270, 30);
        jPanel2.add(price);
        price.setBounds(320, 230, 280, 30);
        jPanel2.add(phone);
        phone.setBounds(320, 190, 280, 30);
        jPanel2.add(city);
        city.setBounds(320, 150, 280, 30);
        jPanel2.add(age);
        age.setBounds(320, 100, 280, 30);

        jLabel6.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 5, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("price");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.add(jLabel6);
        jLabel6.setBounds(50, 230, 180, 30);

        jLabel7.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 5, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("telephone");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.add(jLabel7);
        jLabel7.setBounds(50, 190, 180, 30);
        jPanel2.add(name);
        name.setBounds(320, 60, 280, 30);

        compo_training.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        compo_training.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "sawna ", "fittness", "bodyBuilding" }));
        jPanel2.add(compo_training);
        compo_training.setBounds(320, 20, 280, 30);

        jLabel5.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 5, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("city");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.add(jLabel5);
        jLabel5.setBounds(50, 150, 180, 30);

        jLabel2.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 5, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("age");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.add(jLabel2);
        jLabel2.setBounds(50, 100, 180, 30);

        jLabel4.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 5, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("the name");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.add(jLabel4);
        jLabel4.setBounds(50, 60, 180, 30);

        jLabel3.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 5, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("kind of training");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 20, 180, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/training_project/asdddd.jpeg"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(0, 0, 840, 350);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String jname = this.name.getText();
        //System.out.println("**"+jname+"**");
        String jage = this.age.getText();
        String jprice = this.price.getText();
        String jphone  = this.phone.getText();
         String jtraining = (String )this.compo_training.getSelectedItem();
       
        String jcity = this.city.getText();
        if( this.price.getText().isEmpty() && this.name.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "complete the data ");
            
        } 
       else
        {
          String SQL  = "INSERT INTO gym.hasa "
                      + "( name , phone , price , training_kind , city ,age   ) "
                      + "VALUES ( \" "
                      + jname  +"\""
                      +"," +"\""
                      + jphone +"\""
                      +","
                      +jprice
                      +","+"\""
                      +jtraining+"\""
                      +","+"\""
                      +jcity+"\""
                      + ","
                      + jage
                      + " )";
            
            
            //System.out.println(SQL);
            try {
                connect_me.insert_function(SQL);
            } catch (SQLException ex) {
                Logger.getLogger(second.class.getName()).log(Level.SEVERE, null, ex);
            }
                    
            
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
        menu_frame on = new menu_frame();
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new second().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JTextField city;
    private javax.swing.JComboBox compo_training;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField price;
    // End of variables declaration//GEN-END:variables

   

   
}
